DEPARTMENT_NAMES = [
    "IT",
    "HR",
    "Finance",
    "Sales",
    "Marketing",
    "Operations",
    "Administration",
    "Accounting",
    "Audit",
    "Business Development",
    "Business Intelligence",
    "Communications",
    "Compliance",
    "Customer Experience",
    "Customer Support",
    "Customer Success",
    "Data & Analytics",
    "Design",
    "Engineering",
    "Facilities",
    "Information Security",
    "Infrastructure & Cloud",
    "Legal",
    "Learning & Development",
    "Logistics",
    "Manufacturing",
    "Procurement",
    "Product Management",
    "Project Management",
    "Public Relations",
    "Quality Assurance",
    "Research & Development",
    "Risk Management",
    "Security",
    "Software Development",
    "Supply Chain",
    "Talent Acquisition",
    "Treasury",
    "User Experience (UX/UI)",
]
